export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const AUTH_LOG_OUT = "AUTH_LOG_OUT";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const CLEAR_AUTH_ERRORS = "CLEAR_AUTH_ERRORS";
export const CLEAR_AUTH_MESSAGES = "CLEAR_AUTH_MESSAGES";
