export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_ITEM_RESET = "CART_ADD_RESET";
export const CART_DELETE_ITEM = "CART_DELETE_ITEM";
export const INCREASE_ITEM_QTY = "INCREASE_ITEM_QTY";
export const DECREASE_ITEM_QTY = "DECREASE_ITEM_QTY";
export const CHANGE_PENDING_STATUS = "CHANGE_PENDING_STATUS";
export const CLEAR_CART_ERROR = "CLEAR_CART_ERROR";
