export const SET_STATUS = "SET_STATUS";
export const SET_PRODUCTADDFORM = "SET_PRODUCTADDFORM";
export const SET_TRANSACTIONFORM = "SET_TRANSACTIONFORM";
export const SET_CATEGORYFORM = "SET_CATEGORYFORM";
